In [6]:
import os
import pandas as pd

In [48]:
file_path = 'wine_data.csv'
# Read the CSV file into a DataFrame
df = pd.read_csv(file_path)


df = df.dropna(subset=['Title', 'Description','Country', 'Region', 'Characteristics'])
df.head(5)

,Title,Description,Price,Capacity,Grape,Secondary Grape Varieties,Closure,Country,Unit,Characteristics,Per bottle / case / each,Type,ABV,Region,Style,Vintage,Appellation
1,Bread & Butter 'Winemaker's Selection' Chardon...,This really does what it says on the tin. It’s...,£15.99 per bottle,75CL,Chardonnay,NaN,Natural Cork,USA,10.1,"Vanilla, Almond, Coconut, Green Apple, Peach, ...",per bottle,White,ABV 13.50%,California,Rich & Toasty,2021,Napa Valley
2,"Oyster Bay Sauvignon Blanc 2022, Marlborough",Oyster Bay has been an award-winning gold-stan...,£12.49 per bottle,75CL,Sauvignon Blanc,NaN,Screwcap,New Zealand,9.8,"Tropical Fruit, Gooseberry, Grapefruit, Grass,...",per bottle,White,ABV 13.00%,Marlborough,Crisp & Zesty,2022,NaN
3,Louis Latour Mâcon-Lugny 2021/22,We’ve sold this wine for thirty years – and fo...,£17.99 per bottle,75CL,Chardonnay,NaN,Natural Cork,France,10.1,"Peach, Apricot, Floral, Lemon",per bottle,White,ABV 13.50%,Burgundy,Ripe & Rounded,2022,Macon
4,Bread & Butter 'Winemaker's Selection' Pinot N...,Bread & Butter is that thing that you can coun...,£15.99 per bottle,75CL,Pinot Noir,NaN,Natural Cork,USA,10.1,"Smoke, Black Cherry, Cedar, Raspberry, Red Fruit",per bottle,Red,ABV 13.50%,California,Smooth & Mellow,2021,Napa Valley
6,"La Gioiosa Prosecco DOC, Treviso","In Treviso, Prosecco’s heartland, the locals h...",£12.99 per bottle,75CL,Glera,NaN,Natural Cork,Italy,8.3,"Green Apple, Citrus Fruit, Floral",per bottle,White,ABV 11.00%,Prosecco Doc,Light & Refreshing,NV,NaN

In [49]:
# extract price from the Price 
# format of price is now in "£11.99 per botte"
df['Price'] = df['Price'].str.extract(r'£(\d+\.\d+)').astype(float)

In [42]:
df.describe()

             Price         Unit
count  1104.000000  1104.000000
mean     22.936322    10.194656
std      20.076169     2.104461
min       4.990000     0.000000
25%      11.990000     9.800000
50%      15.990000    10.100000
75%      25.990000    10.500000
max     270.000000    39.000000